global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # 1) Métricas de la app PHP
  - job_name: 'app_oracle'
    metrics_path: /metrics
    static_configs:
      - targets: ['10.100.100.2:80']

  # 2) Node Exporter
  - job_name: 'node_exporter_oracle'
    static_configs:
      - targets: ['10.100.100.2:9100']

  # 3) cAdvisor
  - job_name: 'cadvisor_oracle'
    static_configs:
      - targets: ['10.100.100.2:8080']
